import Link from 'next/link';
import { requirePage } from '@/lib/auth/server';
import CatalogShell from '@/components/AdminCatalog/CatalogShell';
import StockForm from '@/components/AdminInventory/StockForm';
import { inventoryDetail } from '@/lib/inventory/service';
export default async function InventoryProduct({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{page?:string}>}) {
 const session=await requirePage();const {id}=await params;let result;try{result=await inventoryDetail(id,Number((await searchParams).page||1));}catch{return <CatalogShell title="Inventory"><p role="alert">Unable to load stock/history. Check product and history page.</p><Link href="/admin/inventory">Back to inventory</Link></CatalogShell>;}
 const q=result.product.inventory?.quantity??0,r=result.product.inventory?.reserved??0;
 return <CatalogShell title={result.product.model+' · '+result.product.name}><Link href="/admin/inventory" className="underline">Back to inventory</Link><p className="my-5 text-lg">Total {q} · Reserved {r} · Available {q-r}</p>{session.user.role==='ADMIN'&&!result.product.deletedAt?<StockForm productId={id}/>:<p>Read-only: {result.product.deletedAt?'product is deleted':'STAFF can view balances and history'}.</p>}<h2 className="my-5 text-xl">Permanent history ({result.total})</h2><div className="max-w-full overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr>{['Time (UTC) / ID','Actor','Operation / units','Total before → after','Reserved before → after','Note / correction'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{result.history.map(m=><tr className="border-t border-white/10" key={m.id}><td className="p-3">{m.createdAt.toISOString()}<br/>{m.id}</td><td className="p-3">{m.actorName??'Legacy: unknown'}<br/>{m.actorId}</td><td className="p-3">{m.operation??m.type+' (legacy)'} · {m.quantity}</td><td className="p-3">{m.quantityBefore??'?'} → {m.quantityAfter??'?'}</td><td className="p-3">{m.reservedBefore??'?'} → {m.reservedAfter??'?'}</td><td className="max-w-xs break-words p-3">{m.note}<br/>{m.compensationForId&&'Correction of '+m.compensationForId}</td></tr>)}</tbody></table></div>{!result.total&&<p>No movements recorded.</p>}<nav className="mt-5 flex gap-5">{result.page>1&&<Link href={'?page='+(result.page-1)}>Previous</Link>}<span>Page {result.page} / {result.pages}</span>{result.page<result.pages&&<Link href={'?page='+(result.page+1)}>Next</Link>}</nav></CatalogShell>;
}
