'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
type Row = { id: string; name: string; slug: string; parentId?: string | null; brandId?: string | null };
export default function TaxonomyEditor({ options, admin }: { options: { brands: Row[]; categories: Row[] }; admin: boolean }) {
  const router = useRouter(); const [kind, setKind] = useState<'brands' | 'categories'>('brands'); const [selected, setSelected] = useState<Row | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const control = 'mt-1 w-full rounded border border-white/20 bg-[#202020] p-2';
  async function mutate(method: string, data: unknown) {
    setBusy(true); setMessage('');
    try { const response = await fetch(`/api/admin/catalog/${kind}`, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setMessage('Saved to database.'); setSelected(null); router.refresh(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Request failed.'); } finally { setBusy(false); }
  }
  return <div className="space-y-5"><div className="flex gap-5">{(['brands','categories'] as const).map(k => <button key={k} onClick={() => { setKind(k); setSelected(null); setMessage(''); }} className={kind === k ? 'underline' : 'text-stone-400'}>{k === 'brands' ? 'Brands' : 'Categories'}</button>)}</div>{message && <p role="status">{message}</p>}<div className="grid gap-6 md:grid-cols-2"><div className="space-y-2">{options[kind].map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-2 border border-white/10 p-3"><div>{row.parentId && <span className="text-stone-400">{options.categories.find(c => c.id === row.parentId)?.name} / </span>}{row.name}<p className="text-xs text-stone-400">{row.slug}</p></div><div className="flex gap-4"><button disabled={busy} onClick={() => setSelected(row)}>Edit</button>{admin && <button disabled={busy} onClick={() => { if (window.confirm(`Delete ${row.name}? Used records cannot be deleted.`)) mutate('DELETE', { id: row.id }); }}>Delete</button>}</div></div>)}{!options[kind].length && <p>No {kind} yet.</p>}</div><form key={`${kind}-${selected?.id || 'new'}`} onSubmit={event => { event.preventDefault(); mutate(selected ? 'PATCH' : 'POST', { ...Object.fromEntries(new FormData(event.currentTarget)), ...(selected ? { id: selected.id } : {}) }); }}><fieldset disabled={busy} className="min-w-0 space-y-4"><h2 className="text-lg">{selected ? 'Edit' : 'Add'} {kind === 'brands' ? 'brand' : 'category'}</h2><label className="block">Name<input className={control} name="name" required maxLength={191} defaultValue={selected?.name || ''}/></label><label className="block">Slug<input className={control} name="slug" required maxLength={191} defaultValue={selected?.slug || ''}/></label>{kind === 'categories' && <><label className="block">Brand<select className={control} name="brandId" defaultValue={selected?.brandId || ''}><option value="">Any brand</option>{options.brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="block">Parent category<select className={control} name="parentId" defaultValue={selected?.parentId || ''}><option value="">Top level</option>{options.categories.filter(c => c.id !== selected?.id).map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}<div className="flex gap-4"><button className="border border-white/25 p-2">Save</button>{selected && <button type="button" onClick={() => setSelected(null)}>Cancel / Add new</button>}</div></fieldset></form></div></div>;
}
