import Link from 'next/link';
import { requirePage } from '@/lib/auth/server';
import CatalogShell from '@/components/AdminCatalog/CatalogShell';
import { listInventory } from '@/lib/inventory/service';
export default async function InventoryPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 await requirePage();const params=new URLSearchParams();for(const [k,v] of Object.entries(await searchParams))if(typeof v==='string')params.set(k,v);
 let result;try{result=await listInventory(params);}catch{return <CatalogShell title="Inventory"><p role="alert">Inventory unavailable or invalid filters. No sample stock is shown.</p><Link href="/admin/inventory">Reset filters</Link></CatalogShell>;}
 const url=(page:number)=>{const next=new URLSearchParams(params);next.set('page',String(page));return '/admin/inventory?'+next;};const c='min-w-0 rounded border border-white/20 bg-[#202020] p-3';
 return <CatalogShell title="Inventory"><nav className="mb-5"><Link href="/admin/posts">Posts & SEO</Link></nav><p className="mb-4">All stored stock, including deleted products: Total {result.sums.quantity} · Reserved {result.sums.reserved} · Available {result.sums.quantity-result.sums.reserved}</p><form method="get" className="mb-5 grid gap-3 sm:grid-cols-4"><input name="q" placeholder="Search model / name" aria-label="Search inventory" defaultValue={params.get('q')||''} className={c}/><select name="status" aria-label="Product status" defaultValue={params.get('status')||''} className={c}><option value="">All statuses</option>{['DRAFT','ACTIVE','ARCHIVED'].map(s=><option key={s}>{s}</option>)}</select><label className={c}><input type="checkbox" name="deleted" value="yes" defaultChecked={params.get('deleted')==='yes'}/> Include deleted</label><button className={c}>Filter</button></form><p className="mb-3">{result.total} products · Missing inventory means no balance recorded (0); no synthetic stock.</p><div className="max-w-full overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead><tr>{['Model / product','Status','Total','Reserved','Available'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{result.products.map(p=><tr key={p.id} className="border-t border-white/10"><td className="p-3"><Link className="underline" href={'/admin/inventory/'+p.id}>{p.model} · {p.name}</Link></td><td className="p-3">{p.deletedAt?'Deleted':p.status}</td><td className="p-3">{p.inventory?.quantity??0}</td><td className="p-3">{p.inventory?.reserved??0}</td><td className="p-3">{(p.inventory?.quantity??0)-(p.inventory?.reserved??0)}</td></tr>)}</tbody></table></div>{!result.total&&<p>No products match these filters.</p>}<nav className="mt-5 flex gap-5">{result.page>1&&<Link href={url(result.page-1)}>Previous</Link>}<span>Page {result.page} / {result.pages}</span>{result.page<result.pages&&<Link href={url(result.page+1)}>Next</Link>}</nav></CatalogShell>;
}
