import Link from 'next/link';
import { requirePage } from '@/lib/auth/server';
import { catalogOptions, listProducts } from '@/lib/catalog/service';
import CatalogShell from '@/components/AdminCatalog/CatalogShell';
export default async function ProductsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requirePage(['ADMIN', 'STAFF']);
  const params = new URLSearchParams(); for (const [key, value] of Object.entries(await searchParams)) if (typeof value === 'string') params.set(key, value);
  let result;
  try { result = await listProducts(params); } catch { return <CatalogShell title="Products"><p role="alert">Unable to load catalog. Check filters or try again.</p><Link href="/admin/products">Clear filters</Link></CatalogShell>; }
  const { brands, categories } = await catalogOptions(); const { filters } = result;
  function pageUrl(page: number) { const next = new URLSearchParams(params); next.set('page', String(page)); return `/admin/products?${next}`; }
  const control = 'min-w-0 rounded border border-white/20 bg-[#202020] px-3 py-2';
  return <CatalogShell title="Products"><div className="mb-5 flex items-center justify-between gap-3"><p>{result.total} products · Database catalog</p><Link className="border border-white/25 px-3 py-2" href="/admin/products/new">Add product</Link></div><form className="mb-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-6" method="get"><input className={control} name="q" aria-label="Search model, name or slug" placeholder="Search model / name" defaultValue={filters.q}/><select className={control} name="brandId" aria-label="Brand" defaultValue={filters.brandId}><option value="">All brands</option>{brands.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select><select className={control} name="categoryId" aria-label="Category" defaultValue={filters.categoryId}><option value="">All categories</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select className={control} name="status" aria-label="Status" defaultValue={filters.status}><option value="">All statuses</option>{['DRAFT','ACTIVE','ARCHIVED'].map(s => <option key={s}>{s}</option>)}</select><select className={control} name="deleted" aria-label="Deleted" defaultValue={filters.deleted}><option value="live">Current</option><option value="deleted">Deleted</option></select><button className={control}>Filter</button></form><div className="overflow-x-auto border border-white/10"><table className="w-full min-w-[600px] text-left"><thead className="text-stone-400"><tr>{['Model','Name','Brand','Category','Status'].map(h => <th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{result.products.map(p => <tr className="border-t border-white/10" key={p.id}><td className="p-3"><Link className="underline" href={`/admin/products/${p.id}`}>{p.model}</Link></td><td className="p-3">{p.name}</td><td className="p-3">{p.brand.name}</td><td className="p-3">{p.category.name}</td><td className="p-3">{p.deletedAt ? 'Deleted' : p.status}</td></tr>)}</tbody></table>{!result.total && <p className="p-5 text-stone-400">No products match these filters. Add a product or adjust the filters.</p>}</div><div className="mt-5 flex gap-5">{result.page > 1 && <Link href={pageUrl(result.page - 1)}>Previous</Link>}<span>Page {result.page} of {result.pages}</span>{result.page < result.pages && <Link href={pageUrl(result.page + 1)}>Next</Link>}</div></CatalogShell>;
}
